### ISSUE TITLE
Data Vizualizations - General

### ISSUE THREAD

**Issue by chrisdick14** [Data4Democracy/election-transparency#10]
Have an idea for how to bring some clarity and transparency to elections data? We want to see it!

How to get started with the data:
- Download our R package, which has the most up-to-date data
or
- Go over to data.world and grab any of the .csvs that you need.

**Comment by bbrewington** [comment]
Here's a link to the R package: https://github.com/Data4Democracy/election-transparency/tree/master/r-packages/uselections
And the data.world page: https://data.world/data4democracy/election-transparency

**Comment by chrisdick14** [comment]
I see you answered the question before I got to it!

**Comment by chrisdick14** [comment]
Closing this issue so we can have more specific data-viz issues.
