### ISSUE TITLE
Help document the data

### ISSUE THREAD

**Issue by chrisdick14** [Data4Democracy/election-transparency#11]
We need to create a couple of README documents (this is our plan now, but we are open to other options) for each of our data files explaining where we sourced the data as well as a data dictionary for each file. 

All of this information exists, we just need someone to take the time to aggregate it and put it in a good format.

**Comment by stephenfeagin** [comment]
I'd be interested in helping out with this. Also, it looks like the data.world repo doesn't reflect what's in the GitHub repo -- it refers users to the 'voterregus' package, which on Github is called 'uselections.'

**Comment by scottcame** [comment]
Good point about the data.world header.  I'll do a quick post on the slack channel to see if anyone wants to update it...else I can do it this weekend.  On the dataset documentation...want us to assign you this issue...and what do you need to take it from here?  I built a couple of the datasets, so can help.  The biggest challenge is just documenting the source from each state.

**Comment by databeat** [comment]
I just posted the README.md to the data.world summary with a couple adaptations (figured references to the data.world dataset were unecessary and switched link to the GitHub repo). Let me know if there's anything else

**Comment by stephenfeagin** [comment]
Sure, you can go ahead and assign me this issue. This is my first contribution here, so I may need a bit of logistical guidance. Do we have much of any information as to where the state-level data came from? I'd just like to get an idea of how much this task is information consolidation, and how much is information gathering, if that makes sense (I'm totally happy to do it either way!)

**Comment by chrisdick14** [comment]
Thanks for helping out Stephen. The data come from state websites. We have a list I can send you. Probably won't get to it tonight, but I can definitely send it in the morning. Any questions you have just let us know.

**Comment by chrisdick14** [comment]
Ok, here is a link to the document for registration data: https://docs.google.com/spreadsheets/d/118ydIw3FLZnGQCJi4p8wOA_IlH03Cqh2xTJX_dZ1Io0/edit#gid=0

@scottcame will be able to help a little bit more on where all of the results data came from -- and which ones he needed to update or fix. 

Feel free to add anything you think would be useful to the documentation. Some of my starting thoughts are: Where the files were retrieved from, what type of format(s) they are posted in, how often data are released (for the registration), What we have right now, what else we still have to collect, and did we have to request the data.

I am sure there is way more that I am not thinking about, and maybe some of those above are bad ideas, so feel free to make it your own! And, thank you again for being willing to take some of your time to help this project!

**Comment by chrisdick14** [comment]
Covered by a new issue #23
