### ISSUE TITLE
Find and Load useful non-voting data for models

### ISSUE THREAD

**Issue by chrisdick14** [Data4Democracy/election-transparency#16]
Fork the code here: https://github.com/Data4Democracy/election-transparency/blob/master/scripts/read_data.Rmd

*or*

write your own code to pull data from Census (or anywhere else you can find useful data) for us to use in our modelling. The focus right now is on the most recent data we can find for the 2016 election, but down the road we will also want historical data if anyone wants to start with that!

**Comment by ghost** [comment]
I am a beginner - have done some R visualisation and regression. Have joined Kaggle dataset on county features on a range of issues with election results at county level. May be useful for others to explore https://www.kaggle.com/benhamner/2016-us-election . There is also a recent diversity index that has been uploaded https://www.kaggle.com/mikejohnsonjr/us-counties-diversity-index

**Comment by maxpearl** [comment]
That link above for the code to fork is bad - is there a corrected link?

**Comment by chrisdick14** [comment]
You are correct. I forgot I moved that. It is updated now. Sorry about that!

**Comment by chrisdick14** [comment]
Closing this issue for now because we found what we needed for the 2016 models. Will reopen a new more specific issue if needed in the future.
