### ISSUE TITLE
California - Collect historical voter registration data

### ISSUE THREAD

**Issue by chrisdick14** [Data4Democracy/election-transparency#7]
Data: http://www.sos.ca.gov/elections/voter-registration/voter-registration-statistics

**Comment by ptrbates** [comment]
I'd like to get on board with this, is there a description of the task involved? What exactly does "collect" mean, and what data from the link are we interested in? How far back?

**Comment by chrisdick14** [comment]
That is great! Basically, we are looking for someone to download and get the data in a format that looks like the data in the following link: https://data.world/data4democracy/election-transparency/file/PartyRegistration.csv

We are looking to collect as much data as possible into the past, but start with the most current data (other than the 2016 election) and collect at the county level. Using the 15-day report is perfect. Please let me know if you have any further questions or need any help.

**Comment by ptrbates** [comment]
To clarify, the most current data before November 8 at the county level. Including primaries, etc.? or just the general/presidential elections?

**Comment by chrisdick14** [comment]
Let's start with the general elections. We can go back and fill in the primaries later once we get a first set going.

**Comment by ptrbates** [comment]
Does this look like I'm on the right track? If so, I'll keep going with other General Elections. Let me know if anything should be changed or done differently. Is .txt the right file type?
[2014_general_county.txt](https://github.com/Data4Democracy/election-transparency/files/756778/2014_general_county.txt)

**Comment by chrisdick14** [comment]
That looks great! You can stay with a txt if you would like, we have been tending towards .csv, but I don't think it matters much as long as you let us know what the delimiter is.

**Comment by ptrbates** [comment]
csv is fine! The comment box wouldn't let me attach one. I'm done with general elections back to 2002; the 2000 data is in a pdf; I'm looking into how to extract that data. How should I submit what I have? Do you have a naming preference?

**Comment by chrisdick14** [comment]
Go ahead and upload and submit a pull request in the /scripts folder. No naming preference, other than having the state name and years in there, we will be joining it with a larger dataset.

**Comment by chrisdick14** [comment]
Looks like it is text table based, so [Tabula](http://tabula.technology/) would probably work for the PDFs.

**Comment by ptrbates** [comment]
Thanks, Tabula worked well. Sorry to need some hand-holding on the next part (definitely a beginner): the scripts folder is telling me I don't have permission to upload files, and the pull request box is greyed out.

**Comment by chrisdick14** [comment]
Nope, not a beginner thing. I needed to add you to our org. You should be getting an invite shortly. Sorry about that. Let me know if that won't work. If not, you may need to fork the repo, upload on your fork, then do a pull request.

**Comment by ptrbates** [comment]
Ok, done. Thanks for the help!

**Comment by chrisdick14** [comment]
Data just need to be read into R package. Closing issue.
