### ISSUE TITLE
Connecticut - Historical voter registration data

### ISSUE THREAD

**Issue by chrisdick14** [Data4Democracy/election-transparency#9]
Data: http://www.sots.ct.gov/sots/cwp/view.asp?a=3179&q=401492

**Comment by jessicayung** [comment]
Am collecting voter registration data for 2016 and plan to collect the rest of the historical data. Will post an update here once I've collected data for 2010-2014 and 2016 (2015 data is already in the repo).

I'll upload the CSV and the PDF for each year. I will separate the Minor Party Key into a separate CSV (as opposed to how it currently is for the 2015 file).

**Comment by chrisdick14** [comment]
One of us will take a look at this soon. Thank you Jessica!
